## Imports

In [ ]:
import os
import re
import sys
import typing
import gc
import pandas as pd
import pickle
import logging

sys.path.append(
    os.path.join('.','src')
)

from src.models import Pipeline
from src.nodes import *

In [ ]:
logging.basicConfig(filename='logs/logs.log', level=logging.DEBUG)

# Tweets Model

In [ ]:
pipeline = Pipeline('CONFIG_MODEL_TWEETS.json', load_model_data = True)

In [ ]:
d = {
    'train_set_len' : len(pipeline.train_dataset),
    'train_set_tokens' : pipeline.train_dataset.token_len(),
    'val_set_len' : len(pipeline.val_dataset),
    'val_set_tokens' : pipeline.val_dataset.token_len(),
    'test_set_len' : len(pipeline.test_dataset),
    'test_set_tokens' : pipeline.test_dataset.token_len(),
}

In [ ]:
d

In [ ]:
pipeline.perplexity()

In [ ]:
pipeline.train_model()

In [ ]:
pipeline.perplexity()

In [ ]:
pipeline = Pipeline('CONFIG_MODEL_TWEETS.json', load_model_data = False)

In [ ]:
pipeline.load_model('models/tweets/tweets.pth')

In [ ]:
pipeline.generate(start_text = 'all', num_words = 40)

In [ ]:
pipeline.generate(start_text = 'what', num_words = 40)

In [ ]:
pipeline.generate(start_text = 'i like', num_words = 40)

# Wiki Model

In [ ]:
pipeline = Pipeline('CONFIG_MODEL_WIKI.json', load_model_data = True)

In [ ]:
pipeline.perplexity(with_recall = True, with_tqdm = True)

In [ ]:
pipeline.load_model('models/wiki103/wiki103.pth')

In [ ]:
pipeline.perplexity(with_recall = True, with_tqdm = True)

In [ ]:
pipeline.train_model()

In [ ]:
pipeline.perplexity()

In [ ]:
pipeline.generate(start_text = 'all', num_words=40)

In [ ]:
pipeline.generate(start_text = 'what', num_words=40)

In [ ]:
pipeline.generate(start_text = 'i like')

In [ ]:
d = {
    'train_set_len' : len(pipeline.train_dataset),
    'train_set_tokens' : pipeline.train_dataset.token_len(),
    'val_set_len' : len(pipeline.val_dataset),
    'val_set_tokens' : pipeline.val_dataset.token_len(),
    'test_set_len' : len(pipeline.test_dataset),
    'test_set_tokens' : pipeline.test_dataset.token_len(),
}

In [ ]:
d

## FedAVG

In [2]:
from src.federated_pipeline import Federated_AVG

import os
import pickle

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
federated = Federated_AVG(
    "CONFIG_MODEL_TWEETS.json",
    "CONFIG_FEDERATED_TWEETS.json",
    testing = True
)

100%|██████████| 5/5 [00:02<00:00,  2.38it/s]


In [4]:
federated.train(1, save_results = False)

100%|██████████| 5/5 [00:00<00:00, 2839.75it/s]


round 0


  0%|          | 0/5 [00:00<?, ?it/s]

round 1


100%|██████████| 5/5 [00:11<00:00,  2.32s/it]


In [5]:
pd.DataFrame(federated.results)

0  \
perplexity                                                     57.9413   
loss                                                           4.07337   
f1_recall                                                     0.344871   
f3_recall                                                     0.454022   
generate             all former trump donors are reportedly barbara...   
attack_perplexity                                              1038.57   
perplexity_1                                                   173.713   
loss_1                                                         5.15797   
f1_recall_1                                                   0.194994   
f3_recall_1                                                   0.305504   
generate_1           all powerful reasons all the things he is even...   
attack_perplexity_1                                            1038.57   
perplexity_2                                                   99.8095   
loss_2                                                         4.60603   
f1_recall_2                                                    0.25382   
f3_recall_2                                                   0.369271   
generate_2           all of the job endorsing trump trashing dem ju...   
attack_perplexity_2                                            1038.57   
perplexity_3                                                    177.28   
loss_3                                                         5.16575   
f1_recall_3                                                   0.206195   
f3_recall_3                                                   0.312735   
generate_3           all white women accusing that trump chat s off...   
attack_perplexity_3                                            1038.57   
perplexity_4                                                   180.391   
loss_4                                                         5.19024   
f1_recall_4                                                   0.198814   
f3_recall_4                                                   0.308018   
generate_4           all if you believe in all these stories are wo...   
attack_perplexity_4                                            1038.57   
perplexity_5                                                   105.106   
loss_5                                                         4.64917   
f1_recall_5                                                   0.263825   
f3_recall_5                                                   0.382525   
generate_5           all americans want to know who won last nights...   
attack_perplexity_5                                            1038.57   

                                                                     1  
perplexity                                                     85.4144  
loss                                                           4.46081  
f1_recall                                                     0.317658  
f3_recall                                                     0.428005  
generate             all points again for trump won what talking ab...  
attack_perplexity                                              825.814  
perplexity_1                                                   226.091  
loss_1                                                         5.41972  
f1_recall_1                                                   0.195563  
f3_recall_1                                                    0.30778  
generate_1           all the proof were behind you run for the blac...  
attack_perplexity_1                                            825.814  
perplexity_2                                                   131.608  
loss_2                                                         4.87853  
f1_recall_2                                                   0.238541  
f3_recall_2                                                   0.353128  
generate_2           all against donald trump as smart words hes fi...  
attack_perplexit

In [6]:
federated.nodes[1].losses

{'total_loss': [5.318407286768374],
 'loss': [5.316334035733472],
 'reg_loss': [0.002073250146919315]}

## LICCHAVI

In [1]:
from src.federated_pipeline import Federated_LICCHAVI

import os
import pickle
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
federated = Federated_LICCHAVI(
    "CONFIG_MODEL_TWEETS.json",
    "CONFIG_FEDERATED_TWEETS.json",
    testing = True
)

100%|██████████| 5/5 [00:02<00:00,  2.40it/s]


In [3]:
federated.train(2, save_results = False)

  0%|          | 0/5 [00:00<?, ?it/s]

round 0


  0%|          | 0/5 [00:00<?, ?it/s]

round 1
tensor([334.4917], device='cuda:0', grad_fn=<AddBackward0>)
tensor([332.4322], device='cuda:0', grad_fn=<AddBackward0>)
tensor([330.3857], device='cuda:0', grad_fn=<AddBackward0>)
tensor([328.3524], device='cuda:0', grad_fn=<AddBackward0>)
tensor([326.3326], device='cuda:0', grad_fn=<AddBackward0>)
tensor([324.3262], device='cuda:0', grad_fn=<AddBackward0>)
tensor([322.3336], device='cuda:0', grad_fn=<AddBackward0>)
tensor([320.3547], device='cuda:0', grad_fn=<AddBackward0>)
tensor([318.3896], device='cuda:0', grad_fn=<AddBackward0>)
tensor([316.4385], device='cuda:0', grad_fn=<AddBackward0>)
tensor([314.5013], device='cuda:0', grad_fn=<AddBackward0>)
tensor([312.5781], device='cuda:0', grad_fn=<AddBackward0>)
tensor([310.6689], device='cuda:0', grad_fn=<AddBackward0>)
tensor([308.7738], device='cuda:0', grad_fn=<AddBackward0>)
tensor([306.8928], device='cuda:0', grad_fn=<AddBackward0>)
tensor([305.0257], device='cuda:0', grad_fn=<AddBackward0>)
tensor([303.1726], device='cuda:

tensor([136.2396], device='cuda:0', grad_fn=<AddBackward0>)
tensor([135.5490], device='cuda:0', grad_fn=<AddBackward0>)
tensor([134.8625], device='cuda:0', grad_fn=<AddBackward0>)
tensor([134.1800], device='cuda:0', grad_fn=<AddBackward0>)
tensor([133.5015], device='cuda:0', grad_fn=<AddBackward0>)
tensor([132.8270], device='cuda:0', grad_fn=<AddBackward0>)
tensor([132.1564], device='cuda:0', grad_fn=<AddBackward0>)
tensor([131.4898], device='cuda:0', grad_fn=<AddBackward0>)
tensor([130.8270], device='cuda:0', grad_fn=<AddBackward0>)
tensor([130.1682], device='cuda:0', grad_fn=<AddBackward0>)
tensor([129.5132], device='cuda:0', grad_fn=<AddBackward0>)
tensor([128.8620], device='cuda:0', grad_fn=<AddBackward0>)
tensor([128.2147], device='cuda:0', grad_fn=<AddBackward0>)
tensor([127.5711], device='cuda:0', grad_fn=<AddBackward0>)
tensor([126.9313], device='cuda:0', grad_fn=<AddBackward0>)
tensor([126.2952], device='cuda:0', grad_fn=<AddBackward0>)
tensor([125.6628], device='cuda:0', grad

tensor([59.9285], device='cuda:0', grad_fn=<AddBackward0>)
tensor([59.7005], device='cuda:0', grad_fn=<AddBackward0>)
tensor([59.4739], device='cuda:0', grad_fn=<AddBackward0>)
tensor([59.2488], device='cuda:0', grad_fn=<AddBackward0>)
tensor([59.0251], device='cuda:0', grad_fn=<AddBackward0>)
tensor([58.8028], device='cuda:0', grad_fn=<AddBackward0>)
tensor([58.5819], device='cuda:0', grad_fn=<AddBackward0>)
tensor([58.3625], device='cuda:0', grad_fn=<AddBackward0>)
tensor([58.1444], device='cuda:0', grad_fn=<AddBackward0>)
tensor([57.9277], device='cuda:0', grad_fn=<AddBackward0>)
tensor([57.7124], device='cuda:0', grad_fn=<AddBackward0>)
tensor([57.4984], device='cuda:0', grad_fn=<AddBackward0>)
tensor([57.2858], device='cuda:0', grad_fn=<AddBackward0>)
tensor([57.0745], device='cuda:0', grad_fn=<AddBackward0>)
tensor([56.8646], device='cuda:0', grad_fn=<AddBackward0>)
tensor([56.6559], device='cuda:0', grad_fn=<AddBackward0>)
tensor([56.4486], device='cuda:0', grad_fn=<AddBackward0

 20%|██        | 1/5 [00:02<00:09,  2.47s/it]

tensor([334.3996], device='cuda:0', grad_fn=<AddBackward0>)
tensor([332.3390], device='cuda:0', grad_fn=<AddBackward0>)
tensor([330.2913], device='cuda:0', grad_fn=<AddBackward0>)
tensor([328.2569], device='cuda:0', grad_fn=<AddBackward0>)
tensor([326.2358], device='cuda:0', grad_fn=<AddBackward0>)
tensor([324.2283], device='cuda:0', grad_fn=<AddBackward0>)
tensor([322.2344], device='cuda:0', grad_fn=<AddBackward0>)
tensor([320.2542], device='cuda:0', grad_fn=<AddBackward0>)
tensor([318.2879], device='cuda:0', grad_fn=<AddBackward0>)
tensor([316.3355], device='cuda:0', grad_fn=<AddBackward0>)
tensor([314.3970], device='cuda:0', grad_fn=<AddBackward0>)
tensor([312.4725], device='cuda:0', grad_fn=<AddBackward0>)
tensor([310.5620], device='cuda:0', grad_fn=<AddBackward0>)
tensor([308.6656], device='cuda:0', grad_fn=<AddBackward0>)
tensor([306.7831], device='cuda:0', grad_fn=<AddBackward0>)
tensor([304.9147], device='cuda:0', grad_fn=<AddBackward0>)
tensor([303.0602], device='cuda:0', grad

tensor([129.9205], device='cuda:0', grad_fn=<AddBackward0>)
tensor([129.2649], device='cuda:0', grad_fn=<AddBackward0>)
tensor([128.6131], device='cuda:0', grad_fn=<AddBackward0>)
tensor([127.9651], device='cuda:0', grad_fn=<AddBackward0>)
tensor([127.3209], device='cuda:0', grad_fn=<AddBackward0>)
tensor([126.6805], device='cuda:0', grad_fn=<AddBackward0>)
tensor([126.0437], device='cuda:0', grad_fn=<AddBackward0>)
tensor([125.4107], device='cuda:0', grad_fn=<AddBackward0>)
tensor([124.7813], device='cuda:0', grad_fn=<AddBackward0>)
tensor([124.1556], device='cuda:0', grad_fn=<AddBackward0>)
tensor([123.5335], device='cuda:0', grad_fn=<AddBackward0>)
tensor([122.9150], device='cuda:0', grad_fn=<AddBackward0>)
tensor([122.3001], device='cuda:0', grad_fn=<AddBackward0>)
tensor([121.6888], device='cuda:0', grad_fn=<AddBackward0>)
tensor([121.0810], device='cuda:0', grad_fn=<AddBackward0>)
tensor([120.4767], device='cuda:0', grad_fn=<AddBackward0>)
tensor([119.8760], device='cuda:0', grad

tensor([64.7546], device='cuda:0', grad_fn=<AddBackward0>)
tensor([64.4937], device='cuda:0', grad_fn=<AddBackward0>)
tensor([64.2344], device='cuda:0', grad_fn=<AddBackward0>)
tensor([63.9768], device='cuda:0', grad_fn=<AddBackward0>)
tensor([63.7209], device='cuda:0', grad_fn=<AddBackward0>)
tensor([63.4667], device='cuda:0', grad_fn=<AddBackward0>)
tensor([63.2141], device='cuda:0', grad_fn=<AddBackward0>)
tensor([62.9632], device='cuda:0', grad_fn=<AddBackward0>)
tensor([62.7139], device='cuda:0', grad_fn=<AddBackward0>)
tensor([62.4662], device='cuda:0', grad_fn=<AddBackward0>)
tensor([62.2201], device='cuda:0', grad_fn=<AddBackward0>)
tensor([61.9756], device='cuda:0', grad_fn=<AddBackward0>)
tensor([61.7327], device='cuda:0', grad_fn=<AddBackward0>)
tensor([61.4914], device='cuda:0', grad_fn=<AddBackward0>)
tensor([61.2517], device='cuda:0', grad_fn=<AddBackward0>)
tensor([61.0135], device='cuda:0', grad_fn=<AddBackward0>)
tensor([60.7769], device='cuda:0', grad_fn=<AddBackward0

 20%|██        | 1/5 [00:04<00:18,  4.59s/it]


KeyboardInterrupt: 

In [ ]:
pd.DataFrame(federated.results)

In [ ]:
federated.nodes[1].losses

In [ ]:
federated = Federated_LICCHAVI(
    "CONFIG_MODEL_TWEETS.json",
    "CONFIG_FEDERATED_TWEETS.json",
    testing = True
)

In [ ]:
federated.train(1, save_results = False)

In [ ]:
pd.DataFrame(federated.results)

In [ ]:
federated.nodes[1].losses